name : Automated Quality Gate

on : [push, pull_request]

jobs :
  test:
    runs-on : ubuntu-latest

    steps :
      - name : Checkout code
        uses : actions/checkout@v3

      - name : Set up Python
        uses : actions/setup-python@v4
        with : 
          python-version : '3.12'

      - name : Install dependencies
        run : 
          pip install -r requirements.txt
          playwright insatll --with-deps chromium

      - name : Run API Tests
        run : pytest tests/api -v

      - name : Run UI Tests
        run : pytest tests/ui -v
        env :
            HEADLESS : true

      - name : Upload Test Report
        if : always()
        uses : actions/upload-artifacts@v4
        with :
          name : test-Report
          path : report.html        

